// SUBJECTS, PAPERS, SYSTEMS and the complete source question bank.
// Every question maps to exactly one master topic (traceability).

export const SUBJECT_SEEDS = [
  {
    code: "MICRO-IMM-PARA",
    name: "Medical Microbiology, Immunology & Parasitology",
    description:
      "Paper I of the supplied university question bank: general bacteriology, immunology and parasitology.",
  },
  {
    code: "PATH-PHARM",
    name: "Pathology & Pharmacology",
    description:
      "Paper II of the supplied university question bank: general pathology and general pharmacology.",
  },
];

export const PAPER_SEEDS = [
  {
    name: "Paper I",
    subjectCode: "MICRO-IMM-PARA",
    scope: "General Bacteriology · Immunology · Parasitology",
    sortOrder: 1,
  },
  {
    name: "Paper II",
    subjectCode: "PATH-PHARM",
    scope: "General Pathology · General Pharmacology",
    sortOrder: 2,
  },
];

export const SYSTEM_SEEDS = [
  {
    slug: "general-microbiology",
    paperName: "Paper I",
    name: "General Bacteriology",
    unitLabel: "Unit I",
    intro:
      "Structure of the bacterial cell, growth and culture, sterilization and disinfection.",
    sortOrder: 1,
  },
  {
    slug: "immunology",
    paperName: "Paper I",
    name: "Immunology",
    unitLabel: "Unit II",
    intro:
      "Antibodies and immunoglobulins, the complement system, and hypersensitivity reactions.",
    sortOrder: 2,
  },
  {
    slug: "parasitology",
    paperName: "Paper I",
    name: "Parasitology",
    unitLabel: "Unit III",
    intro:
      "Malaria (Plasmodium vivax), intestinal amoebiasis and soil-transmitted helminths.",
    sortOrder: 3,
  },
  {
    slug: "general-pathology",
    paperName: "Paper II",
    name: "General Pathology",
    unitLabel: "Unit IV",
    intro:
      "Cell injury and cell death, acute inflammation, and the biology of neoplasia.",
    sortOrder: 1,
  },
  {
    slug: "pharmacology",
    paperName: "Paper II",
    name: "General Pharmacology",
    unitLabel: "Unit V",
    intro:
      "Antimicrobial chemotherapy (penicillins) and autacoid drug pharmacology (NSAIDs/aspirin).",
    sortOrder: 2,
  },
];

export interface QuestionSeed {
  systemSlug: string;
  topicSlug: string | null;
  qtype: "laq" | "sn" | "saq";
  text: string;
  stars: number;
  timesAsked: number;
  needsDiagram?: boolean;
  needsLabDx?: boolean;
  needsMechanism?: boolean;
  needsLifeCycle?: boolean;
  needsComparison?: boolean;
  needsClassification?: boolean;
  keyPoints: string;
}

export const QUESTION_SEEDS: QuestionSeed[] = [
  // ─────────────────────────── UNIT I — GENERAL BACTERIOLOGY ───────────────────────────
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-cell-envelope",
    qtype: "laq",
    text: "Describe the structure of the bacterial cell with a labelled diagram. Add a note on the Gram-positive and Gram-negative cell wall and the principle of Gram staining.",
    stars: 5,
    timesAsked: 3,
    needsDiagram: true,
    needsComparison: true,
    keyPoints: `Prokaryotic plan (nucleoid, 70S ribosomes, no organelles) · essential vs accessory structures table · peptidoglycan = NAG–NAM + cross-links · Gram+ thick PG + teichoic acids, no outer membrane · Gram− thin PG + periplasm + outer membrane with LPS/lipid A + porins · Gram stain: CV → iodine → alcohol (critical) → safranin · diagram of both envelopes.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-growth-culture-media",
    qtype: "laq",
    text: "Classify culture media. Describe selective and indicator (differential) media in detail with examples.",
    stars: 3,
    timesAsked: 2,
    needsClassification: true,
    keyPoints: `By consistency (liquid/semi-solid/solid) and by function (basal, enriched, selective, indicator, enrichment, transport, anaerobic) · selective = inhibitors (MacConkey bile salts, LJ malachite green, TCBS) · indicator = visible differentiation (MacConkey LF pink, blood agar haemolysis) · MacConkey is BOTH.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "sterilization-disinfection",
    qtype: "laq",
    text: "Define sterilization and disinfection. Describe the principle, procedure, controls and uses of the autoclave.",
    stars: 4,
    timesAsked: 2,
    needsMechanism: true,
    keyPoints: `Definitions verbatim · principle: steam under pressure 121 °C at 15 psi kills spores · procedure: expel air → 15 psi → 15 min holding time → slow cooling · controls: Browne's tube, tape, thermocouple, G. stearothermophilus spores (biological) · uses + exceptions (oils/powders → hot air oven).`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-cell-envelope",
    qtype: "sn",
    text: "Bacterial capsule — structure, composition and functions.",
    stars: 3,
    timesAsked: 2,
    keyPoints: `Polysaccharide (poly-D-glutamate in B. anthracis) · antiphagocytic — major virulence factor · adhesion · Quellung reaction · list of encapsulated organisms.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-cell-envelope",
    qtype: "sn",
    text: "Bacterial spore (endospore).",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Dormant resistant structure of Bacillus/Clostridium · dipicolinic acid + Ca · survival NOT reproduction · killed by autoclaving · position diagnostic.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-growth-culture-media",
    qtype: "sn",
    text: "Bacterial growth curve in batch culture with diagram.",
    stars: 4,
    timesAsked: 2,
    needsDiagram: true,
    keyPoints: `Four phases — lag, log, stationary, decline · log = generation time + drug sensitivity · stationary = growth equals death · plot log viable count vs time.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-growth-culture-media",
    qtype: "sn",
    text: "Transport media — purpose and examples.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Maintain viability without multiplication · Stuart's, alkaline peptone water, buffered glycerol saline · for delicate organisms during transit to lab.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-cell-envelope",
    qtype: "sn",
    text: "Gram staining — procedure and interpretation.",
    stars: 4,
    timesAsked: 2,
    keyPoints: `CV → iodine → decolorizer → safranin · CV–I complex trapped by thick PG · over/under-decolorization errors · result interpretation.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-cell-envelope",
    qtype: "sn",
    text: "Flagella and pili — structure and functions.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Flagellin; arrangement patterns (mono/lopho/amphi/peritrichous); H antigen · pili: pilin; adhesion; sex pilus = conjugation.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "sterilization-disinfection",
    qtype: "sn",
    text: "Pasteurization — methods and uses.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Holder 63 °C × 30 min · HTST/flash 72 °C × 15 s · milk — kills pathogens but NOT spores → disinfection, not sterilization.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "sterilization-disinfection",
    qtype: "saq",
    text: "Define sterilization, disinfection, antisepsis and asepsis.",
    stars: 3,
    timesAsked: 2,
    keyPoints: `Four definitions verbatim — spores killed only in sterilization; antisepsis = living tissue; asepsis = prevention of entry.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-cell-envelope",
    qtype: "saq",
    text: "Enumerate the accessory structures of bacteria with one function each.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Capsule (antiphagocytic) · flagella (motility) · pili (adhesion/conjugation) · plasmids (resistance/toxin genes) · spores (survival).`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-growth-culture-media",
    qtype: "saq",
    text: "Define generation time. Give one example.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Time for population to double in log phase · E. coli ≈ 20 min · M. tuberculosis 18–24 h.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-growth-culture-media",
    qtype: "saq",
    text: "Enumerate the methods of anaerobic culture.",
    stars: 1,
    timesAsked: 1,
    keyPoints: `Robertson's cooked meat medium · thioglycollate broth · McIntosh–Fildes/GasPak jar · anaerobic glove box · reduced methylene blue indicator.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-cell-envelope",
    qtype: "saq",
    text: "Name four encapsulated bacteria.",
    stars: 1,
    timesAsked: 1,
    keyPoints: `S. pneumoniae · H. influenzae · N. meningitidis · Klebsiella pneumoniae (+ B. anthracis, Cryptococcus).`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "sterilization-disinfection",
    qtype: "saq",
    text: "Enumerate chemical disinfectants with one example and use each.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Alcohols 70% (skin) · glutaraldehyde 2% (endoscopes) · hypochlorites (surfaces/water) · chlorhexidine (skin) · phenolics · cetrimide.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "sterilization-disinfection",
    qtype: "saq",
    text: "Why is 70% alcohol a better disinfectant than absolute alcohol?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Water required for protein denaturation · absolute alcohol forms a surface protein shell preventing penetration.`,
  },
  {
    systemSlug: "general-microbiology",
    topicSlug: "bacterial-growth-culture-media",
    qtype: "saq",
    text: "Enumerate special culture media with the organism each is used for.",
    stars: 2,
    timesAsked: 2,
    keyPoints: `LJ — M. tuberculosis · TCBS — V. cholerae · tellurite — C. diphtheriae · Bordet–Gengou — B. pertussis · chocolate agar — Neisseria/Haemophilus · SDA — fungi · Wilson–Blair — S. Typhi.`,
  },

  // ─────────────────────────── UNIT II — IMMUNOLOGY ───────────────────────────
  {
    systemSlug: "immunology",
    topicSlug: "immunoglobulins",
    qtype: "laq",
    text: "Describe the structure and functions of immunoglobulins with a labelled diagram. Compare the five classes of immunoglobulins.",
    stars: 5,
    timesAsked: 3,
    needsDiagram: true,
    needsComparison: true,
    keyPoints: `H2L2 plan; V/C domains; hinge; Fab vs Fc · papain → 2Fab+Fc, pepsin → F(ab′)2 · eight functions · five-class comparison table · primary vs secondary response.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "complement-system",
    qtype: "laq",
    text: "Describe the classical pathway of complement activation with a diagram. Enumerate the functions of complement.",
    stars: 4,
    timesAsked: 2,
    needsDiagram: true,
    needsMechanism: true,
    keyPoints: `Ag–Ab → C1 → C4+C2 → C3 convertase C4b2a → C3 → C5 convertase C4b2a3b → MAC C5b–9 · anaphylatoxins C3a/C5a · C3b opsonin · six functions · heat-labile 56 °C/30 min.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "hypersensitivity",
    qtype: "laq",
    text: "Define hypersensitivity. Describe the Gell and Coombs classification and discuss Type I hypersensitivity in detail.",
    stars: 5,
    timesAsked: 3,
    needsComparison: true,
    keyPoints: `Definition · four-type master table · Type I: sensitization → IgE on mast cells → cross-linking → histamine (immediate) + leukotrienes (late) · clinical examples of each type · anaphylaxis + adrenaline rationale.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "immunoglobulins",
    qtype: "sn",
    text: "IgM — structure and properties.",
    stars: 4,
    timesAsked: 2,
    keyPoints: `Pentamer + J chain; largest; first antibody of primary response; best complement fixer; ABO isoagglutinins; fetal IgM = intrauterine infection marker.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "immunoglobulins",
    qtype: "sn",
    text: "Secretory IgA.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Dimer + J chain + secretory piece; mucosal surfaces; colostrum/saliva/tears; first-line mucosal defence; selective IgA deficiency = commonest primary immunodeficiency.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "immunoglobulins",
    qtype: "sn",
    text: "Primary and secondary (anamnestic) immune response.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Lag, titre, class (IgM → IgG), affinity, duration · memory B-cell basis · vaccination/booster logic.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "immunoglobulins",
    qtype: "sn",
    text: "Antigen–antibody reactions in vitro.",
    stars: 3,
    timesAsked: 2,
    keyPoints: `Agglutination, precipitation, neutralization, complement fixation, immunofluorescence, ELISA, Western blot — one principle + one use each.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "complement-system",
    qtype: "sn",
    text: "Functions of the complement system.",
    stars: 4,
    timesAsked: 2,
    keyPoints: `Lysis (MAC) · opsonization (C3b) · inflammation (C3a/C5a) · chemotaxis (C5a) · immune-complex clearance · B-cell enhancement.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "hypersensitivity",
    qtype: "sn",
    text: "Differentiate Type II and Type III hypersensitivity with examples.",
    stars: 3,
    timesAsked: 1,
    needsComparison: true,
    keyPoints: `Type II: antibody against FIXED cell/matrix antigen (transfusion reactions, HDN, Goodpasture) · Type III: CIRCULATING complexes deposit (serum sickness, SLE, Arthus) · both IgG/IgM + complement.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "hypersensitivity",
    qtype: "sn",
    text: "Type IV (delayed-type) hypersensitivity.",
    stars: 3,
    timesAsked: 2,
    keyPoints: `T-cell mediated; 24–72 h · Mantoux/tuberculin · contact dermatitis · granulomatous · graft rejection · four subtypes.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "immunoglobulins",
    qtype: "saq",
    text: "Define antibody, antigen and hapten.",
    stars: 2,
    timesAsked: 2,
    keyPoints: `Antibody = plasma-cell glycoprotein combining specifically with inducing antigen · antigen = induces + reacts · hapten = reacts only, needs carrier.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "immunoglobulins",
    qtype: "saq",
    text: "Enumerate the classes of immunoglobulins with one key property of each.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `IgG (placental transfer) · IgM (first response, pentamer) · IgA (secretory/mucosal) · IgD (B-cell receptor) · IgE (allergy/parasites).`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "complement-system",
    qtype: "saq",
    text: "What is the membrane attack complex (MAC)?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `C5b + C6–C9 transmembrane pore → osmotic lysis · terminal pathway shared by all activation routes · deficiency → Neisseria infections.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "immunoglobulins",
    qtype: "saq",
    text: "Why is IgM the most efficient complement-fixing antibody?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Pentamer offers multiple adjacent Fc sites — a single IgM can bind C1q (needs ≥2 Fc); IgG needs two adjacent molecules.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "hypersensitivity",
    qtype: "saq",
    text: "Enumerate the mediators released in Type I hypersensitivity.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Preformed: histamine, tryptase, heparin, ECF · newly synthesized: leukotrienes C4/D4/E4, PGD2, PAF · cytokines IL-4, IL-5, IL-13.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "complement-system",
    qtype: "saq",
    text: "What is opsonization? Name the opsonins.",
    stars: 2,
    timesAsked: 2,
    keyPoints: `Coating of microbes to enhance phagocytosis · opsonins: C3b (and iC3b) + IgG-Fc.`,
  },
  {
    systemSlug: "immunology",
    topicSlug: "hypersensitivity",
    qtype: "saq",
    text: "List examples of Type II hypersensitivity diseases.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Transfusion reactions · HDN (Rh) · autoimmune haemolytic anaemia · Goodpasture syndrome · Graves disease · myasthenia gravis · drug-induced (methyldopa).`,
  },

  // ─────────────────────────── UNIT III — PARASITOLOGY ───────────────────────────
  {
    systemSlug: "parasitology",
    topicSlug: "plasmodium-vivax",
    qtype: "laq",
    text: "Describe the life cycle of Plasmodium vivax with a neatly labelled diagram.",
    stars: 5,
    timesAsked: 3,
    needsDiagram: true,
    needsLifeCycle: true,
    keyPoints: `Man = intermediate, Anopheles = definitive · sporozoite infective · hepatic exo-erythrocytic schizogony + hypnozoites · erythrocytic cycle 48 h · gametocytes · mosquito sporogony (zygote → ookinete → oocyst → sporozoites) · two-territory diagram.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "plasmodium-vivax",
    qtype: "laq",
    text: "Describe the laboratory diagnosis of malaria.",
    stars: 4,
    timesAsked: 2,
    needsLabDx: true,
    keyPoints: `Blood during fever before drugs · thick film = detection, thin film = species/parasitaemia (Giemsa) · vivax features (Schüffner's dots, enlarged RBCs) · RDT HRP-2/pLDH · QBC, PCR · algorithm flow.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "entamoeba-histolytica",
    qtype: "laq",
    text: "Describe the morphology, pathogenesis and laboratory diagnosis of Entamoeba histolytica.",
    stars: 4,
    timesAsked: 2,
    needsLabDx: true,
    keyPoints: `Trophozoite (bull's-eye nucleus, ingested RBCs) vs cyst (4 nuclei, chromatoid bodies) · flask-shaped ulcer · liver abscess anchovy pus · stool microscopy + antigen ELISA + serology for abscess · metronidazole then luminal agent.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "ascaris-lumbricoides",
    qtype: "sn",
    text: "Life cycle of Ascaris lumbricoides with diagram.",
    stars: 4,
    timesAsked: 2,
    needsLifeCycle: true,
    needsDiagram: true,
    keyPoints: `Embryonated egg infective · hatch in intestine → portal vein → liver → lungs → trachea → swallowed → adult in jejunum · Loeffler syndrome · complications · diagram of the lung loop.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "plasmodium-vivax",
    qtype: "sn",
    text: "Malarial parasites in a stained blood film (diagnostic morphology).",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Thin vs thick film roles · ring forms, trophozoites, schizonts, gametocytes · vivax: enlarged RBCs + Schüffner's dots · falciparum: multiple rings, appliqué forms, banana gametocyte.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "entamoeba-histolytica",
    qtype: "sn",
    text: "Cyst and trophozoite of Entamoeba histolytica.",
    stars: 3,
    timesAsked: 2,
    needsComparison: true,
    keyPoints: `Trophozoite: 15–30 µm, motile, one bull's-eye nucleus, ingested RBCs · cyst: 10–15 µm, up to 4 nuclei, chromatoid bodies · cyst = infective, trophozoite = pathogenic · comparison table.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "ascaris-lumbricoides",
    qtype: "sn",
    text: "Complications of ascariasis.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Loeffler syndrome (lung phase) · intestinal obstruction in children · biliary/pancreatic ascariasis · appendicitis · aberrant migration.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "plasmodium-vivax",
    qtype: "sn",
    text: "Radical cure of vivax malaria — basis and caution.",
    stars: 3,
    timesAsked: 1,
    needsMechanism: true,
    keyPoints: `Chloroquine = blood schizonticide (clinical cure) · primaquine kills hepatic HYPOZOITES = radical cure, prevents relapse · check G6PD first (haemolysis).`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "plasmodium-vivax",
    qtype: "saq",
    text: "Name the infective stage of P. vivax and the diagnostic stage of malaria.",
    stars: 3,
    timesAsked: 2,
    keyPoints: `Infective = sporozoite (mosquito bite) · diagnostic = intra-erythrocytic parasites on blood smear.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "plasmodium-vivax",
    qtype: "saq",
    text: "Enumerate the human malarial species with their fever periodicity.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `P. vivax 48 h benign tertian · P. falciparum 48 h malignant tertian · P. malariae 72 h quartan · P. ovale 48 h · P. knowlesi quotidian.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "ascaris-lumbricoides",
    qtype: "saq",
    text: "What is Loeffler syndrome?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Eosinophilic pneumonitis during larval lung migration — cough, fleeting infiltrates, eosinophilia; also hookworm/Strongyloides.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "plasmodium-vivax",
    qtype: "saq",
    text: "Why does P. vivax malaria relapse?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Dormant hepatic HYPOZOITES persist after blood-stage cure → reactivate weeks–months later → fresh erythrocytic waves.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "entamoeba-histolytica",
    qtype: "saq",
    text: "What is 'anchovy sauce' pus and where is it found?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Sterile brown necrotic material in amoebic liver abscess — liquefied hepatocytes, few inflammatory cells; trophozoites at abscess wall.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "plasmodium-vivax",
    qtype: "saq",
    text: "Enumerate the preventive measures against malaria.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `IRS, ITN/LLIN, larviciding/source reduction, repellents, chemoprophylaxis, early diagnosis + treatment, surveillance.`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "ascaris-lumbricoides",
    qtype: "saq",
    text: "How do you identify the fertilized egg of Ascaris lumbricoides?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Oval, thick shell, MAMILLATED albuminous coat, golden-brown, unsegmented ovum; differentiate from hookworm eggs (segmented).`,
  },
  {
    systemSlug: "parasitology",
    topicSlug: "entamoeba-histolytica",
    qtype: "saq",
    text: "What is the pathognomonic microscopic feature of E. histolytica trophozoites?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `ERYTHROPHAGOCYTOSIS — ingested RBCs in cytoplasm; distinguishes E. histolytica from E. dispar.`,
  },

  // ─────────────────────────── UNIT IV — GENERAL PATHOLOGY ───────────────────────────
  {
    systemSlug: "general-pathology",
    topicSlug: "cell-injury-necrosis-apoptosis",
    qtype: "laq",
    text: "Define necrosis. Classify and describe the types of necrosis. Differentiate necrosis from apoptosis.",
    stars: 5,
    timesAsked: 3,
    needsComparison: true,
    needsClassification: true,
    keyPoints: `Definition · nuclear sequence pyknosis → karyorrhexis → karyolysis · six types with sites · gross + microscopic recognition · master necrosis-vs-apoptosis table.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "acute-inflammation",
    qtype: "laq",
    text: "Define acute inflammation. Describe its pathogenesis including the vascular and cellular events with diagrams.",
    stars: 5,
    timesAsked: 3,
    needsDiagram: true,
    needsMechanism: true,
    keyPoints: `Cardinal signs · vascular flowchart (vasodilatation → permeability → exudate) · cellular flowchart (margination → rolling → adhesion → transmigration → chemotaxis → phagocytosis) · mediators · outcomes.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "neoplasia",
    qtype: "laq",
    text: "Define neoplasia. Differentiate benign from malignant tumours and describe the routes of metastasis.",
    stars: 5,
    timesAsked: 2,
    needsComparison: true,
    needsDiagram: true,
    keyPoints: `Willis definition · benign vs malignant table · metastasis = defining criterion · three routes with carcinoma/sarcoma rule + exceptions · metastasis diagram · Krukenberg, Virchow node.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "cell-injury-necrosis-apoptosis",
    qtype: "sn",
    text: "Mechanisms of cell injury.",
    stars: 3,
    timesAsked: 1,
    needsMechanism: true,
    keyPoints: `ATP depletion · mitochondrial damage · calcium influx · oxidative stress · reversible vs irreversible features · point of no return.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "acute-inflammation",
    qtype: "sn",
    text: "Chemical mediators of inflammation.",
    stars: 4,
    timesAsked: 2,
    keyPoints: `Histamine · PGs · leukotrienes · bradykinin · C3a/C5a · IL-1/TNF · IL-8 · NO — source + action table.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "acute-inflammation",
    qtype: "sn",
    text: "Outcomes of acute inflammation.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Resolution · suppuration/abscess · organization/fibrosis · chronic inflammation · systemic spread (bacteraemia → septicaemia, pyaemia).`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "neoplasia",
    qtype: "sn",
    text: "Characteristics of malignant cells (anaplasia).",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Pleomorphism · hyperchromasia · high N:C ratio · atypical mitoses · loss of polarity · necrosis · invasion.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "neoplasia",
    qtype: "sn",
    text: "Routes of metastasis with examples.",
    stars: 4,
    timesAsked: 2,
    needsDiagram: true,
    keyPoints: `Lymphatic (carcinomas → nodes; Virchow node) · haematogenous (sarcomas → liver/lungs; RCC/HCC/choriocarcinoma exceptions) · seeding (Krukenberg).`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "acute-inflammation",
    qtype: "sn",
    text: "Phagocytosis — steps and killing mechanisms.",
    stars: 3,
    timesAsked: 1,
    needsMechanism: true,
    keyPoints: `Recognition (opsonins IgG-Fc, C3b) → engulfment (phagosome → phagolysosome) → killing: respiratory burst H2O2–MPO–halide + oxygen-independent systems · CGD example.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "acute-inflammation",
    qtype: "sn",
    text: "Transudate versus exudate.",
    stars: 2,
    timesAsked: 1,
    needsComparison: true,
    keyPoints: `Protein <3 vs >3 g/dL · SG <1.012 vs >1.012 · hydrostatic/oncotic vs permeability mechanism · examples.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "acute-inflammation",
    qtype: "saq",
    text: "Enumerate the cardinal signs of inflammation with their basis.",
    stars: 3,
    timesAsked: 2,
    keyPoints: `Rubor + calor = vasodilatation · tumor = exudate · dolor = PGs + bradykinin · functio laesa (Virchow) = pain + swelling.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "cell-injury-necrosis-apoptosis",
    qtype: "saq",
    text: "Define necrosis, apoptosis and gangrene.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Necrosis = pathological death + inflammation · apoptosis = programmed, no inflammation · gangrene = necrosis + putrefaction of a limb/bowel.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "neoplasia",
    qtype: "saq",
    text: "Define oncogene and tumour suppressor gene with one example each.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Oncogene = gain-of-function growth promoter (RAS, MYC) · tumour suppressor = brake requiring two-hit loss (RB, p53).`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "neoplasia",
    qtype: "saq",
    text: "Enumerate tumour markers with their associated tumours.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `AFP — HCC · CEA — colorectal · PSA — prostate · CA-125 — ovary · β-hCG — choriocarcinoma · calcitonin — medullary thyroid · Bence-Jones — myeloma.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "neoplasia",
    qtype: "saq",
    text: "Define metastasis. Name the commonest sites of metastasis.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Secondary deposits discontinuous with primary — defining feature of malignancy · commonest sites: liver and lungs; then bone, brain, adrenals.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "acute-inflammation",
    qtype: "saq",
    text: "What is the respiratory burst of phagocytes?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `NADPH-oxidase-mediated O2 consumption → superoxide → H2O2 → MPO + halide → HOCl = main bactericidal system.`,
  },
  {
    systemSlug: "general-pathology",
    topicSlug: "cell-injury-necrosis-apoptosis",
    qtype: "saq",
    text: "Why is the brain infarct liquefactive while the kidney infarct is coagulative?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Brain is rich in lytic enzymes and lipids with little stroma → enzymatic digestion dominates → liquefaction; solid organs retain protein scaffolding → coagulative.`,
  },

  // ─────────────────────────── UNIT V — GENERAL PHARMACOLOGY ───────────────────────────
  {
    systemSlug: "pharmacology",
    topicSlug: "penicillins",
    qtype: "laq",
    text: "Classify penicillins. Describe the mechanism of action, therapeutic uses and adverse effects of penicillins. Add a note on β-lactamase inhibitors.",
    stars: 5,
    timesAsked: 3,
    needsMechanism: true,
    needsClassification: true,
    keyPoints: `Four sub-groups table · MOA three levels (β-lactam mimics D-Ala–D-Ala → PBPs → no cross-links → autolysin lysis) · uses table with rationale · ADR table · clavulanate/sulbactam/tazobactam logic.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "nsaids-aspirin",
    qtype: "laq",
    text: "Classify NSAIDs. Describe the mechanism of action, uses and adverse effects of aspirin. Compare aspirin with paracetamol.",
    stars: 5,
    timesAsked: 2,
    needsMechanism: true,
    needsDiagram: true,
    needsComparison: true,
    keyPoints: `Classification table · AA pathway diagram · COX-1 vs COX-2 · aspirin irreversible · uses incl. low-dose antiplatelet · ADRs with mechanisms · aspirin vs paracetamol table.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "penicillins",
    qtype: "sn",
    text: "Mechanisms of resistance to penicillins.",
    stars: 4,
    timesAsked: 2,
    needsMechanism: true,
    keyPoints: `β-lactamase hydrolysis (commonest) · altered PBPs (MRSA mecA/PBP2a; pneumococci) · porin loss · efflux pumps.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "nsaids-aspirin",
    qtype: "sn",
    text: "Adverse effects of aspirin.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `GI ulcer/bleed (COX-1 block) · bleeding tendency (TXA2) · renal · bronchospasm (LOX shunt) · Reye syndrome · salicylism · hypersensitivity.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "nsaids-aspirin",
    qtype: "sn",
    text: "COX-1 versus COX-2.",
    stars: 3,
    timesAsked: 1,
    needsComparison: true,
    keyPoints: `COX-1 constitutive — gastric protection, platelet TXA2, renal flow · COX-2 inducible — inflammation · COX-2 selective drugs: less GI, more CV risk.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "penicillins",
    qtype: "sn",
    text: "Why is clavulanic acid combined with amoxicillin?",
    stars: 3,
    timesAsked: 2,
    needsMechanism: true,
    keyPoints: `Clavulanate irreversibly inhibits β-lactamases, protecting amoxicillin · restores activity vs β-lactamase producers · same logic: sulbactam, tazobactam.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "nsaids-aspirin",
    qtype: "sn",
    text: "Low-dose aspirin as an antiplatelet drug.",
    stars: 3,
    timesAsked: 1,
    keyPoints: `Irreversible COX-1 acetylation · platelets anucleate → no enzyme regeneration → TXA2 suppressed for platelet lifespan · secondary prevention of MI/stroke.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "penicillins",
    qtype: "saq",
    text: "Define antibiotic. Differentiate bactericidal from bacteriostatic drugs.",
    stars: 2,
    timesAsked: 1,
    needsComparison: true,
    keyPoints: `Antibiotic = substance of microbial origin that kills/inhibits other microbes · cidal = kills (penicillins) · static = inhibits growth, relies on host immunity (tetracyclines).`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "penicillins",
    qtype: "saq",
    text: "Enumerate the β-lactamase inhibitors.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Clavulanic acid · sulbactam · tazobactam — always paired with a β-lactam partner.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "nsaids-aspirin",
    qtype: "saq",
    text: "What is Reye syndrome?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Hepatic encephalopathy in children with viral illness given aspirin — hence no aspirin below ~12–16 years.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "nsaids-aspirin",
    qtype: "saq",
    text: "Why should aspirin be avoided in children with viral fever?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Risk of Reye syndrome (fatty liver + encephalopathy); paracetamol is the safe antipyretic.`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "penicillins",
    qtype: "saq",
    text: "Enumerate the classes of penicillins with one example each.",
    stars: 3,
    timesAsked: 1,
    needsClassification: true,
    keyPoints: `Natural (benzylpenicillin) · penicillinase-resistant (cloxacillin) · aminopenicillins (amoxicillin) · antipseudomonal (piperacillin).`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "nsaids-aspirin",
    qtype: "saq",
    text: "Name the toxic metabolite and antidote in paracetamol overdose.",
    stars: 2,
    timesAsked: 1,
    keyPoints: `NAPQI (via CYP450) depletes glutathione → hepatic necrosis · antidote = N-acetylcysteine (restores glutathione).`,
  },
  {
    systemSlug: "pharmacology",
    topicSlug: "penicillins",
    qtype: "saq",
    text: "What is the Jarisch–Herxheimer reaction?",
    stars: 2,
    timesAsked: 1,
    keyPoints: `Fever/rigors hours after first anti-syphilis dose — cytokine release from killed spirochaetes; not a drug allergy.`,
  },
];
