import Link from "next/link";
import { figures, atlasEntries, topics, systems } from "@/lib/static-data";

export default function AtlasPage() {
  const topicById=new Map(topics.map((t)=>[t.id,t]));
  const systemById=new Map(systems.map((s)=>[s.id,s]));
  const kinds=["classification","comparison","labdx","lifecycle","mechanism"];
  return (
    <div className="rise space-y-6">
      <header><p className="text-[11px] font-extrabold uppercase tracking-[0.18em] text-crimson">End-of-book atlas layers</p><h1 className="mt-1.5 font-display text-[30px] font-semibold leading-tight">Master Atlases</h1><p className="mt-2 max-w-3xl text-[14px] leading-relaxed text-ink-soft">Every figure, classification, comparison, laboratory protocol, life cycle and mechanism in the book, delivered as static revision material.</p></header>
      <section><h2 className="mb-3 font-display text-[21px] font-semibold">Master Diagram Atlas</h2><div className="grid gap-5 lg:grid-cols-2">{figures.map((f,i)=>{const sys=f.systemId?systemById.get(f.systemId):null;return <figure key={f.id} className="figure-card"><div className="figure-svg" dangerouslySetInnerHTML={{__html:f.svg}}/><figcaption><span className="figure-tag">FIGURE {i+1} {sys?"· "+sys.name:""}</span><span className="figure-title">{f.title}</span><p className="figure-caption">{f.caption}</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><div className="rounded-md border border-line bg-white p-2.5"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-crimson">Must-label structures</p><p className="mt-1 text-[11.5px] leading-relaxed text-ink-soft">{f.labels}</p></div><div className="rounded-md border border-line bg-white p-2.5"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-teal">Exam drawing sequence</p><p className="mt-1 whitespace-pre-line text-[11.5px] leading-relaxed text-ink-soft">{f.drawingSteps}</p></div></div>{f.examTip&&<p className="mt-2 rounded-md bg-amber-wash px-2.5 py-1.5 text-[11.5px] font-semibold text-amber">Examiner note: {f.examTip}</p>}</figcaption></figure>})}</div></section>
      {kinds.map((kind)=><section key={kind}><h2 className="mb-3 font-display text-[21px] font-semibold">{kind==="labdx"?"Lab Diagnosis":kind==="lifecycle"?"Life Cycles":kind==="comparison"?"Comparisons":kind==="classification"?"Classifications":"Mechanisms"}</h2><div className="grid gap-3 md:grid-cols-2">{atlasEntries.filter((e)=>e.kind===kind).map((e)=><div key={e.id} className="panel p-4"><h3 className="font-display text-[16px] font-semibold">{e.title}</h3><p className="mt-1.5 text-[13px] leading-relaxed text-ink-soft">{e.summary}</p>{e.topicId&&topicById.get(e.topicId)&&<Link href={"/topics/"+e.topicId} className="mt-2.5 inline-block text-[12.5px] font-bold text-teal-deep underline decoration-teal/40 underline-offset-4">Full treatment → {topicById.get(e.topicId)?.title}</Link>}</div>)}</div></section>)}
    </div>
  );
}